### ISSUE TITLE
A few issues with QtCrypt

### ISSUE THREAD

**Issue by jedisct1** [trashctor/QtCrypt#1]
Hi,

And thanks for QtCrypt; it looks pretty nice.

However, it looks like the file format has some issues. It encrypts chunks of `BUFFER_SIZE_WITHOUT_MAC` bytes, generating and prepending a random nonce before each block.

So, blocks can be reordered without this being noticed. Blocks can be deleted without it being noticed. Blocks can be duplicated without it being noticed.

Do not forget that nonces don't have to be unpredictable; they just have to be unique for each message, for a given key. So, you can just set an initial nonce and increment it: this will prevent reordering/duplicating blocks. Or use `hash(previous encrypted block)` as a nonce. And you need a way to mark the end of the file, so that you know that it hasn't been truncated. This can be a specific block type, or an empty block, or you can send the complete file size in the file header.

Also feel free to take a look at https://github.com/jedisct1/blobcrypt

**Comment by sergeevabc** [comment]
What cipher is used by QtCrypt exactly?
